### ISSUE TITLE
[WIP]【必ず】やることリスト

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/SwiftLab#4]
やることリスト - 親 Issues
---
 
- [x] Swift TODO ドキュメント化 #3 
- [ ] Swift TODO 記事化
- [ ] Swift TODO サイト化 #1  
- [x] Swift TODO GA設定 #2
